# Site settings
title: Titles are overrated
email: enzo.aquino@gmail.com
author: Enzo Aquino
description: "Random thoughts"
baseurl: "blog.enzoaquino.com" 
url: "blog.enzoaquino.com" 
google_analytics:
animated: false
show_related_posts: false

# Build settings
markdown: kramdown
permalink: pretty
paginate: 3
sass:
  compressed: true
